#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [[ "${1-}" == "" ]]; then
    cmd=( bash )
else
    cmd=("${@}")
fi

exec docker run -ti romanesco/image:1.0 "${cmd[@]}"
