#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

trap 'exit $status' INT TERM && trap "kill 0" EXIT

status=0

scripts/server --port 50506 --wait &
sleep 0.3
scripts/test-runner || status=$?
